/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#ffb4aa',
        surface: '#121414',
        'on-background': '#e2e2e2',
        'secondary-fixed': '#e5e2e1',
        'surface-container-lowest': '#0c0f0f',
        'surface-bright': '#37393a',
        'on-secondary-fixed': '#1c1b1b',
        'secondary-container': '#4a4949',
        'secondary-fixed-dim': '#c8c6c5',
        'primary-fixed-dim': '#ffb4aa',
        'on-surface-variant': '#e9bcb6',
        'inverse-surface': '#e2e2e2',
        'on-primary-fixed-variant': '#930007',
        'primary-fixed': '#ffdad5',
        'inverse-on-surface': '#2f3131',
        'outline-variant': '#5e3f3b',
        'tertiary-fixed-dim': '#a7c8ff',
        'on-tertiary': '#003061',
        'primary-container': '#e50914',
        'on-tertiary-fixed-variant': '#004689',
        'on-primary-container': '#fff7f6',
        'surface-dim': '#121414',
        'on-primary-fixed': '#410001',
        error: '#ffb4ab',
        background: '#121414',
        'on-tertiary-container': '#f8f9ff',
        'on-secondary-container': '#bab8b7',
        'on-secondary-fixed-variant': '#474646',
        secondary: '#c8c6c5',
        'on-primary': '#690003',
        tertiary: '#a7c8ff',
        'on-error': '#690005',
        'on-surface': '#e2e2e2',
        'error-container': '#93000a',
        'inverse-primary': '#c0000c',
        'surface-container-high': '#282a2b',
        'surface-container': '#1e2020',
        'on-tertiary-fixed': '#001b3c',
        'on-secondary': '#313030',
        'surface-container-low': '#1a1c1c',
        outline: '#af8782',
        'tertiary-container': '#0072d7',
        'tertiary-fixed': '#d5e3ff',
        'surface-variant': '#333535',
        'surface-tint': '#ffb4aa',
        'on-error-container': '#ffdad6',
        'surface-container-highest': '#333535',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        xs: '4px',
        lg: '24px',
        sm: '8px',
        gutter: '24px',
        md: '16px',
        unit: '4px',
        xl: '40px',
        margin: '48px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-xl': ['40px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-out',
        'slide-up': 'slideUp 0.4s ease-out',
        'pulse-slow': 'pulse 3s infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
}
